name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run package
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: 'EXIF Reader'
          path: 'deploy/darwin/build/*'
